### PR TITLE
Refactor Values, Slice, and Kvslice in D/O/Array,Hash

### LINKED ISSUE #268: Data::Object::Hash::Func::Slice - confusing name
I think that [Data::Object::Hash::slice](https://metacpan.org/pod/Data::Object::Hash#slice) may be a confusing name. In perl, there are two types of hash slices:

```
my %hash = (
    a => 'b',
    c => 'd',
);
```

- [value slice](https://perlmaven.com/hash-slice)

```
my ($a, $c) = @hash{qw/a c/};

# $a holds 'b'
# $c holds 'd'
```

- [keyvalue slice](https://www.effectiveperlprogramming.com/2014/07/perl-5-20-introduces-keyvalue-slices/)
```
my @keyvalue_slice = %hash{qw/a c/};

# @keyvalue_slice holds 'a', 'b', 'c', 'd'
```

The current `slice` method is almost like perl 5.20's keyvalue slice, but it wraps it in a hashref.

### PR DESCRIPTION
**Pull request by srchulo**
Make Values, Slice, and KvSlice correspond their meanings in Perl

Closes #268

### CODE REVIEW

**Comment by iamalnewkirk** [comment]
@srchulo I cleaned up this PR a bit before reviewing. You'll need to pull the updates before making changes!

**Comment by iamalnewkirk** [comment]
@srchulo Sorry for not explaining this earlier; The test folders represent major shifts in the frameworks API with `0.90` being the latest. The other folders are retained as regression tests, for backward compatibility. We should only be adding tests to the latest version of tests, i.e. `0.90`.

Also, as in the Ruby language, we want to try to maintain some kind of parity between object method names as it makes intuiting and using the methods between objects predictable, e.g. if you're going to change what `slice`, `value` and `kvslice` mean and do, you should also make those changes in `Data::Object::Array` too.

**Comment by srchulo** [comment]
@iamalnewkirk thanks for explaining that. I'll delete the added `t/0.01/data/object/hash/kvslice.t`. However, I think I should leave the modified `t/0.01/data/object/hash/slice.t` and `t/0.01/data/object/hash/values.t` since they will break/be inconsistent otherwise?

For `Data::Object::Array`, so you think it would be good to add a `kvslice` that returned a hash of `index => value`?

**Comment by iamalnewkirk** [comment]
@srchulo I've begun marking tests in `t/0.01` and `t/0.50` as deprecated, given that I've begun breaking with backward compatibility. I think you should do the same and move all newer tests under the `t/0.90` folder. We're almost at ready to release `v2.00` which will introduce a core API stability policy, see https://github.com/iamalnewkirk/do/projects/14#card-26076498.

**Comment by srchulo** [comment]
@iamalnewkirk I've modified `Array::Func::Values` to match `Hash::Func::Values`, and I've added `Array::Func::Kvslice`. `Array::Func::Slice` seemed okay the way that it was.

**Comment by iamalnewkirk** [comment]
Closing this PR in favor of https://github.com/iamalnewkirk/do/pull/304; please see the review there and push to that branch!

**Pull request closed without merging**
